name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend.Dockerfile
          push: true
          tags: lycohana/todos-frontend:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend.Dockerfile
          push: true
          tags: |
            ${{ steps.semver.outputs.version }}
            latest

      # ===== Version bump, changelog generation, commit and release =====
      - name: Bump version and create tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: patch
          tag_prefix: v

      - name: Generate Changelog for new tag
        if: steps.tag_version.outputs.new_tag != ''
        uses: scottbrenner/generate-changelog-action@master
        with:
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          futureRelease: ${{ steps.tag_version.outputs.new_tag }}
          output: CHANGELOG.md
          issues: true
          pullRequests: true
          compareLink: true

      - name: Commit CHANGELOG.md back to repository
        if: steps.tag_version.outputs.new_tag != ''
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(changelog): update for ${{ steps.tag_version.outputs.new_tag }} [skip ci]"
          file_pattern: CHANGELOG.md
          branch: main

      - name: Create GitHub Release
        if: steps.tag_version.outputs.new_tag != ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: ${{ steps.tag_version.outputs.new_tag }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
